import { Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import AppContextProvider from "./context/AppContext";
import "./globals.css";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system"
          enableSystem>
          <AppContextProvider>{children}</AppContextProvider>        </ThemeProvider>
      </body>
    </html>
  );
}
